#!/usr/bin/env bash
# ============================================================
# Pi Container — Entrypoint
# ============================================================
# Auto-generated by wpi.
# Do not edit — changes will be overwritten on next build.
# ============================================================
set -eo pipefail

HOST_UID="${HOST_UID:-1000}"
HOST_GID="${HOST_GID:-1000}"
# USERNAME and USER_HOME are passed by the launcher so the in-container user
# mirrors the host user name and home directory (e.g. <user> / /Users/<user>).
USERNAME="${HOST_USERNAME:-pi-user}"
USER_HOME="${HOST_HOME:-/home/${USERNAME}}"

PI_HOME="${USER_HOME}/.pi"
PI_AGENT_HOME="${PI_HOME}/agent"

# ── Match pi-user UID/GID to host user ──────────────────
if [ "$(id -u pi-user)" != "${HOST_UID}" ]; then
  groupmod -g "${HOST_GID}" pi-user 2>/dev/null || true
  usermod -u "${HOST_UID}" -g "${HOST_GID}" pi-user 2>/dev/null || true
fi

# ── Rename user/group to match host username ────────────
if [ "${USERNAME}" != "pi-user" ]; then
  # groupmod -n must come before usermod -l (group rename is independent)
  groupmod -n "${USERNAME}" pi-user 2>/dev/null || true
  usermod -l "${USERNAME}" pi-user 2>/dev/null || true
fi

# ── Set home directory ──────────────────────────────────
# The host home path may differ from the Linux default (e.g. /Users/<user> on macOS).
# Create the directory hierarchy, point the user record at it, and fix ownership.
mkdir -p "${USER_HOME}"
usermod -d "${USER_HOME}" "${USERNAME}" 2>/dev/null || true
chown "${HOST_UID}:${HOST_GID}" "${USER_HOME}" 2>/dev/null || true

# ── Copy default settings if none exist ────────────────
PI_SETTINGS="${PI_AGENT_HOME}/settings.json"
DEFAULT_SETTINGS="/opt/pi/default-settings.json"
if [ ! -f "${PI_SETTINGS}" ]; then
  mkdir -p "${PI_AGENT_HOME}"
  cp "${DEFAULT_SETTINGS}" "${PI_SETTINGS}"
  chown "${HOST_UID}:${HOST_GID}" "${PI_SETTINGS}" 2>/dev/null || true
fi

# ── Ensure configured mounted volume paths are writable
# PI_MOUNT_PATHS (comma-separated) is passed by the launcher and lists container paths
if [ -n "${PI_MOUNT_PATHS:-}" ]; then
  IFS=',' read -r -a __pi_mount_paths <<< "${PI_MOUNT_PATHS}"
  for __mp in "${__pi_mount_paths[@]}"; do
    # Only touch paths that look like absolute container paths
    if [ -z "${__mp}" ]; then
      continue
    fi
    # Only change ownership if the path already exists (e.g., a mounted volume)
    if [ -e "${__mp}" ]; then
      chown "${HOST_UID}:${HOST_GID}" "${__mp}" 2>/dev/null || true
    fi
  done
fi

gosu "${USERNAME}" pi install /opt/pi-package

# ── Set git user info from host ────────────────────────
if [ -n "${GIT_USER_NAME}" ]; then
  gosu "${USERNAME}" git config --global user.name "${GIT_USER_NAME}"
fi
if [ -n "${GIT_USER_EMAIL}" ]; then
  gosu "${USERNAME}" git config --global user.email "${GIT_USER_EMAIL}"
fi

# ── Drop privileges and run command as host user ────────
exec gosu "${USERNAME}" "$@"