// ============================================================
// Tests for templates.ts — Dockerfile and entrypoint generation
// ============================================================

import { describe, it, expect } from "vitest";
import { generateDockerfile, generateEntrypoint } from "./templates";
import { PI_VERSION } from "./config";

describe("generateDockerfile", () => {
  it("includes the pinned pi version in ARG", () => {
    const df = generateDockerfile();
    expect(df).toContain(`ARG PI_VERSION=${PI_VERSION}`);
  });

  it("uses multi-stage build", () => {
    const df = generateDockerfile();
    expect(df).toContain("FROM node:22-bookworm-slim AS builder");
    expect(df).toContain("FROM node:22-bookworm-slim AS runtime");
  });

  it("installs pi in builder stage", () => {
    const df = generateDockerfile();
    expect(df).toContain("npm install -g --ignore-scripts @earendil-works/pi-coding-agent@${PI_VERSION}");
  });

  it("installs team package dependencies in builder stage", () => {
    const df = generateDockerfile();
    expect(df).toContain("COPY package/package.json /build/package/");
    expect(df).toContain("cd /build/package && npm install --omit=dev");
  });

  it("installs runtime OS dependencies", () => {
    const df = generateDockerfile();
    expect(df).toContain("git");
    expect(df).toContain("gosu");
    expect(df).toContain("docker-ce-cli");
  });

  it("creates pi-user", () => {
    const df = generateDockerfile();
    expect(df).toContain("useradd -m -s /bin/bash pi-user");
  });

  it("copies pi from builder", () => {
    const df = generateDockerfile();
    expect(df).toContain("COPY --from=builder /usr/local/lib/node_modules");
  });

  it("copies team package source and deps", () => {
    const df = generateDockerfile();
    expect(df).toContain("COPY package/ /opt/pi-package/");
    expect(df).toContain("COPY --from=builder /build/package/node_modules /opt/pi-package/node_modules");
  });

  it("copies settings and entrypoint", () => {
    const df = generateDockerfile();
    expect(df).toContain("COPY settings/default-settings.json /opt/pi/default-settings.json");
    expect(df).toContain("COPY entrypoint.sh /opt/pi/entrypoint.sh");
  });

  it("sets workspace and entrypoint", () => {
    const df = generateDockerfile();
    expect(df).toContain("WORKDIR /build");
    expect(df).toContain('ENTRYPOINT ["/opt/pi/entrypoint.sh"]');
    expect(df).toContain('CMD ["pi"]');
  });

  it("includes do-not-edit header", () => {
    const df = generateDockerfile();
    expect(df).toContain("Auto-generated by wpi");
    expect(df).toContain("Do not edit");
  });

  it("appends extension block when provided", () => {
    const df = generateDockerfile("RUN apt-get install -y python3");
    expect(df).toContain("# ---------- Extension from .pi/wpi.yml ----------");
    expect(df).toContain("RUN apt-get install -y python3");
    // Should appear after the template's CMD
    const cmdIndex = df.indexOf('CMD ["pi"]');
    const extIndex = df.indexOf("RUN apt-get install -y python3");
    expect(extIndex).toBeGreaterThan(cmdIndex);
  });

  it("does not include extension comment when no extension provided", () => {
    const df = generateDockerfile();
    expect(df).not.toContain("Extension from .pi/wpi.yml");
  });

  it("injects pi version in all ARG lines", () => {
    const df = generateDockerfile();
    const argLines = df.split("\n").filter((line: string) => line.startsWith("ARG PI_VERSION="));
    expect(argLines.length).toBe(2);
    expect(argLines[0]).toBe(`ARG PI_VERSION=${PI_VERSION}`);
    expect(argLines[1]).toBe(`ARG PI_VERSION=${PI_VERSION}`);
  });

  it("includes Docker CLI by default", () => {
    const df = generateDockerfile();
    expect(df).toContain("docker-ce-cli");
  });

  it("includes both extension and Docker CLI when extension is provided", () => {
    const df = generateDockerfile("RUN echo extension");
    expect(df).toContain("docker-ce-cli");
    expect(df).toContain("Extension from .pi/wpi.yml");
    expect(df).toContain("RUN echo extension");
  });
});

describe("generateEntrypoint", () => {
  it("starts with bash shebang", () => {
    const sh = generateEntrypoint();
    expect(sh.startsWith("#!/usr/bin/env bash")).toBe(true);
  });

  it("sets pipefail", () => {
    const sh = generateEntrypoint();
    expect(sh).toContain("set -eo pipefail");
  });

  it("matches UID/GID to host user", () => {
    const sh = generateEntrypoint();
    expect(sh).toContain("groupmod");
    expect(sh).toContain("usermod");
    expect(sh).toContain("${HOST_UID:-1000}");
    expect(sh).toContain("${HOST_GID:-1000}");
  });

  it("references pi config paths", () => {
    const sh = generateEntrypoint();
    expect(sh).toContain('PI_AGENT_HOME="${PI_HOME}/agent"');
  });

  it("skips recursive chown on mounted config (ownership handled via UID/GID match)", () => {
    const sh = generateEntrypoint();
    // No recursive chown on ${PI_HOME} — it hangs on virtualized mounts
    expect(sh).not.toContain("chown -R pi-user:pi-user");
    // Single-file chown still present for files we create (uses numeric UID:GID)
    expect(sh).toContain('chown "${HOST_UID}:${HOST_GID}" "${PI_SETTINGS}"');
  });

  it("copies default settings if none exist", () => {
    const sh = generateEntrypoint();
    expect(sh).toContain('"${PI_AGENT_HOME}/settings.json"');
    expect(sh).toContain("/opt/pi/default-settings.json");
    expect(sh).toContain('if [ ! -f "${PI_SETTINGS}" ]; then');
  });

  it("installs the team package via pi install", () => {
    const sh = generateEntrypoint();
    expect(sh).toContain('gosu "${USERNAME}" pi install /opt/pi-package');
  });

  it("drops privileges with gosu", () => {
    const sh = generateEntrypoint();
    expect(sh).toContain('exec gosu "${USERNAME}" "$@"');
  });

  it("does not contain TEAM_PACKAGES (removed)", () => {
    const sh = generateEntrypoint();
    expect(sh).not.toContain("TEAM_PACKAGES");
  });

  it("is valid bash (no template interpolation artifacts)", () => {
    const sh = generateEntrypoint();
    expect(sh).not.toContain("${piVersion}");
    expect(sh).not.toContain("${config.");
    expect(sh).not.toContain("undefined");
  });
});
